services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: flaskapp
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data