"""Added getVacancies boolean to User

Revision ID: 235315f32909
Revises: 67a91ec1f211
Create Date: 2022-12-09 12:41:36.894494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235315f32909'
down_revision = '67a91ec1f211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('getVacancies', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('users', 'getVacancies')
    # ### end Alembic commands ###
