"""added connection request table

Revision ID: 7ea8869c1114
Revises: 7d788e5108c2
Create Date: 2022-12-04 22:39:23.056395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea8869c1114'
down_revision = '7d788e5108c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromUser', sa.Integer(), nullable=True),
    sa.Column('toUser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_requests')
    # ### end Alembic commands ###
