"""first users test

Revision ID: e8c721df92d0
Revises: 46fd32e8203a
Create Date: 2022-11-22 14:32:45.022276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c721df92d0'
down_revision = '46fd32e8203a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'authenticated')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
